chore: import 7.2.10

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -96,6 +96,7 @@ WITH_X11=1
 WITH_ALSA=1
 WITH_PULSE=1
 WITH_DBUS=1
+WITH_DXVK=1
 WITH_DEVMAPPER=1
 WITH_KMODS=1
 WITH_OPENGL=1
@@ -106,8 +107,8 @@ WITH_VNC=0
 WITH_EXTPACK=1
 WITH_DOCS=1
 WITH_LIBVPX=1
-WITH_LIBOGG=0
-WITH_LIBVORBIS=0
+WITH_LIBOGG=1
+WITH_LIBVORBIS=1
 WITH_LIBTPMS=1
 WITH_LIBLZMA=1
 BUILD_LIBXML2=
@@ -716,11 +717,11 @@ check_libxml2()
 extern "C" int main(void)
 {
   printf("found version %s", LIBXML_DOTTED_VERSION);
-#if LIBXML_VERSION >= 20626
+#if LIBXML_VERSION >= 20904
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 2.6.26 or higher\n");
+  printf(", expected version 2.9.4 or higher\n");
   return 1;
 #endif
 }
@@ -750,11 +751,11 @@ EOF
 extern "C" int main(void)
 {
   printf("found version %s", LIBXML_DOTTED_VERSION);
-#if LIBXML_VERSION >= 20626
+#if LIBXML_VERSION >= 20904
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 2.6.26 or higher\n");
+  printf(", expected version 2.9.4 or higher\n");
   return 1;
 #endif
 }
@@ -843,11 +844,11 @@ extern "C" int main(void)
 {
   printf("found version %s", OPENSSL_VERSION_TEXT);
   SSL_library_init();
-#if OPENSSL_VERSION_NUMBER >= 0x10001000
+#if OPENSSL_VERSION_NUMBER >= 0x10002000
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 1.0.1 or higher\n");
+  printf(", expected version 1.0.2 or higher\n");
   return 1;
 #endif
 }
@@ -910,11 +911,11 @@ check_z()
 extern "C" int main(void)
 {
   printf("found version %s", ZLIB_VERSION);
-#if ZLIB_VERNUM >= 0x1210
+#if ZLIB_VERNUM >= 0x12b0
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 1.2.1 or higher\n");
+  printf(", expected version 1.2.11 or higher\n");
   return 1;
 #endif
 }
@@ -961,7 +962,7 @@ EOF
       echo "endif" >> $CNF
     fi
   else
-    echo "not found -- builing liblzf from in-tree code."
+    echo "not found -- building liblzf from in-tree code."
   fi
 }
 
@@ -1050,11 +1051,11 @@ check_curl()
 extern "C" int main(void)
 {
   printf("found version %s", LIBCURL_VERSION);
-#if 10000*LIBCURL_VERSION_MAJOR + 100*LIBCURL_VERSION_MINOR + LIBCURL_VERSION_PATCH >= 71901
+#if 10000*LIBCURL_VERSION_MAJOR + 100*LIBCURL_VERSION_MINOR + LIBCURL_VERSION_PATCH >= 76101
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 7.19.1 or higher\n");
+  printf(", expected version 7.61.1 or higher\n");
   return 1;
 #endif
 }
@@ -1170,11 +1171,11 @@ extern "C" int main(int argc, char** argv)
 {
   printf("found version %d.%d.%d",
          SDL_MAJOR_VERSION, SDL_MINOR_VERSION, SDL_PATCHLEVEL);
-#if SDL_VERSION_ATLEAST(1,2,7)
+#if SDL_VERSION_ATLEAST(1,2,15)
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 1.2.7 or higher\n");
+  printf(", expected version 1.2.15 or higher\n");
   return 1;
 #endif
 }
@@ -1214,11 +1215,11 @@ extern "C" int main(void)
 {
   printf("found version %d.%d.%d",
          SDL_TTF_MAJOR_VERSION, SDL_TTF_MINOR_VERSION, SDL_TTF_PATCHLEVEL);
-#if 10000*SDL_TTF_MAJOR_VERSION + 100*SDL_TTF_MINOR_VERSION + SDL_TTF_PATCHLEVEL >= 20006
+#if 10000*SDL_TTF_MAJOR_VERSION + 100*SDL_TTF_MINOR_VERSION + SDL_TTF_PATCHLEVEL >= 20011
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 2.0.6 or higher\n");
+  printf(", expected version 2.0.11 or higher\n");
   return 1;
 #endif
 }
@@ -1246,11 +1247,11 @@ extern "C" int main(void)
 {
   printf("found version %d.%d.%d",
          SND_LIB_MAJOR, SND_LIB_MINOR, SND_LIB_SUBMINOR);
-#if 10000*SND_LIB_MAJOR + 100*SND_LIB_MINOR + SND_LIB_SUBMINOR >= 10014
+#if 10000*SND_LIB_MAJOR + 100*SND_LIB_MINOR + SND_LIB_SUBMINOR >= 10106
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 1.0.14 or higher\n");
+  printf(", expected version 1.1.6 or higher\n");
   return 1;
 #endif
 }
@@ -1273,11 +1274,11 @@ check_pulse()
 extern "C" int main(void)
 {
   printf("found version %s API version %d", pa_get_headers_version(), PA_API_VERSION);
-#if PA_API_VERSION >= 9
+#if PA_API_VERSION >= 12
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 0.9.0 (API version 9) or higher\n");
+  printf(", expected version 0.12.0 (API version 12) or higher\n");
   return 1;
 #endif
 }
@@ -1695,7 +1696,7 @@ EOF
       fail
     fi
   else
-    log_failure "qt6 not found"
+    log_failure "qt6 not found, expected version $QT6MAJ.$QT6MIN or higher"
     fail
   fi
 }
@@ -1725,25 +1726,26 @@ extern "C" int main(void)
   int verMinor = VPX_VERSION_MINOR(version);
   int verPatch = VPX_VERSION_PATCH(version);
   printf("found version %d.%d.%d", verMajor, verMinor, verPatch);
-  if (   verMajor == 1 && verMinor >= 0
-      || verMajor == 0 && verMinor == 9 && verPatch >= 5)
+  if (verMajor == 1 && verMinor >= 7)
   {
       printf(", OK.\n");
       return 0;
   }
   else
   {
-      printf(", expected version 0.9.5 or higher\n");
+      printf(", expected version 1.7.0 or higher\n");
       return 1;
    }
 }
 EOF
       [ -n "$INCVPX" ] && I_INCVPX=`prefix_I "$INCVPX"`
-      if test_compile "$LIBVPX $I_INCVPX" vpx vpx; then
+      if test_compile "$LIBVPX $I_INCVPX" vpx vpx nofatal; then
         if test_execute; then
           cnf_append "SDK_VBoxLibVpx_INCS" "$INCVPX"
           cnf_append "SDK_VBoxLibVpx_LIBS" "`strip_l "$LIBVPX"`"
-          fi
+        fi
+      else
+        echo "not found -- building libvpx from in-tree code."
       fi
     fi
   fi
@@ -1947,11 +1949,11 @@ int main(void)
   printf("found version %d.%d.%d",  LINUX_VERSION_CODE / 65536,
                                    (LINUX_VERSION_CODE % 65536) / 256,
                                     LINUX_VERSION_CODE          % 256);
-#if LINUX_VERSION_CODE > KERNEL_VERSION(2,4,0)
+#if LINUX_VERSION_CODE > KERNEL_VERSION(2,6,32)
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 2.4.0 or higher\n");
+  printf(", expected version 2.6.32 or higher\n");
   return 1;
 #endif
 }
@@ -2108,11 +2110,11 @@ extern "C" int main(void)
 {
   Py_Initialize();
   printf("found version %s", PY_VERSION);
-#if PY_VERSION_HEX >= 0x02060000
+#if PY_VERSION_HEX >= 0x02070000
   printf(", OK.\n");
   return 0;
 #else
-  printf(", expected version 2.6 or higher\n");
+  printf(", expected version 2.7 or higher\n");
   return 1;
 #endif
 }
@@ -2169,6 +2171,20 @@ check_java()
   fi
 }
 
+
+#
+# Check for stuff required for building DXVK
+#
+check_dxvk()
+{
+  test_header "DXVK support"
+  if ! which_wrapper glslangValidator > /dev/null; then
+    echo "  glslangValidator not found, automatically disabling DXVK support"
+    WITH_DXVK=0
+  else
+    log_success
+  fi
+}
 
 #
 # Setup wine
@@ -2469,6 +2485,7 @@ EOF
 [ $WITH_ALSA    -eq 1 ] && echo "  --disable-alsa           disable the ALSA sound backend"
 [ $WITH_PULSE   -eq 1 ] && echo "  --disable-pulse          disable the PulseAudio backend"
 [ $WITH_DBUS    -eq 1 ] && echo "  --disable-dbus           don't use DBus and hal for hardware detection"
+[ $WITH_DXVK    -eq 1 ] && echo "  --disable-dxvk           don't use DXVK"
 [ $WITH_KMODS   -eq 1 ] && echo "  --disable-kmods          don't build Linux kernel modules (host and guest)"
 [ $WITH_OPENGL  -eq 1 ] && echo "  --disable-opengl         disable OpenGL support (2D & 3D)"
 [ $WITH_QT6     -eq 0 ] && echo "  --enable-qt6             enable Qt6 detection"
@@ -2533,7 +2550,7 @@ EOF
 #
 
 # test if we are OSE
-if [ $OSE -eq 1 -a -r "`cd \`dirname $0\`; pwd`/src/VBox/RDP/server/server.cpp" ]; then
+if [ $OSE -eq 1 -a -r "`cd \`dirname $0\`; pwd`/src/VBox/ExtPacks/Puel/ExtPack.xml" ]; then
   OSE=0
   # Set this as a reminder to print a log message once we know the path of the
   # log file
@@ -2564,6 +2581,7 @@ elif [ "$OS" = "haiku" ]; then
   WITH_ALSA=0
   WITH_PULSE=0
   WITH_DBUS=0
+  WITH_DXVK=0
   WITH_KMODS=0
   WITH_XPCOM=0
   BUILD_LIBXSLT=1
@@ -2683,6 +2701,9 @@ for option in "$@"; do
       ;;
     --disable-dbus)
       [ $WITH_DBUS -eq 1 ] && WITH_DBUS=0
+      ;;
+    --disable-dxvk)
+      [ $WITH_DXVK -eq 1 ] && WITH_DXVK=0
       ;;
     --disable-kmods)
       [ $WITH_KMODS -eq 1 ] && WITH_KMODS=0
@@ -2976,6 +2997,7 @@ if [ $ONLY_ADDITIONS -eq 0 ]; then
   [ $WITH_QT6    -eq 1 ] && check_qt6
   [ $WITH_PYTHON -eq 1 ] && check_python
   [ $WITH_JAVA   -eq 1 ] && check_java
+  [ $WITH_DXVK   -eq 1 -a $OSE -eq 1 ] && check_dxvk
 
   # PulseAudio
   if [ $WITH_PULSE -eq 1 ]; then
@@ -3006,6 +3028,9 @@ if [ "$OS" = "linux" ]; then
     fi
     if [ $WITH_DBUS -eq 0 ]; then
       cnf_append "VBOX_WITH_DBUS" ""
+    fi
+    if [ $WITH_DXVK -eq 0 ]; then
+      cnf_append "VBOX_WITH_DXVK" ""
     fi
     if [ $WITH_DEVMAPPER -eq 1 ]; then
       check_libdevmapper
